require('dotenv').config({ path: '../.env' });

const {
  MEDIA_PATH,
  TRASH_DIR,
  ARCHIVE_DIR,
  API_SERVER_URL,
  API_KEY,
  PROVIDER,
  MAIN_DB_PATH,
  TEMP_DB_PATH,
  TIMEOUT_CAMERA_OFF_ALERT,
  ARCHIVE_DAYS,
  MAX_FILE_SIZE,
  BOT_TOKEN,
  MAX_REQUESTS_COUNT,
  REQUEST_TIMEOUT,
  SEND_PACKAGE_TIMEOUT,
} = process.env;

module.exports = {
  MEDIA_PATH: MEDIA_PATH || './MEDIA_PATH',
  TRASH_DIR: TRASH_DIR || './TRASH_DIR',
  ARCHIVE_DIR: ARCHIVE_DIR || './ARCHIVE_DIR',
  API_SERVER_URL: API_SERVER_URL || 'http://localhost:3000',
  API_KEY: API_KEY || 'test',
  PROVIDER: PROVIDER || 'test-provider',
  MAIN_DB_PATH,
  TEMP_DB_PATH,
  TIMEOUT_CAMERA_OFF_ALERT: TIMEOUT_CAMERA_OFF_ALERT || 3600000,
  ARCHIVE_DAYS,
  MAX_FILE_SIZE: MAX_FILE_SIZE || 250000,
  BOT_TOKEN: BOT_TOKEN || new Error('Set bot token'),
  MAX_REQUESTS_COUNT: MAX_REQUESTS_COUNT || 50,
  REQUEST_TIMEOUT: REQUEST_TIMEOUT || 1000,
  SEND_PACKAGE_TIMEOUT: SEND_PACKAGE_TIMEOUT || 5000,
};
