module.exports = {
  JSON_SENT: 'JSON_SENT',
  APP_ERROR: 'APP_ERROR',
  APP_INFO: 'APP_INFO',
  API_ERROR: 'API_ERROR',
  CAMERA_ONLINE: 'CAMERA_ONLINE',
  CAMERA_OFFLINE: 'CAMERA_OFFLINE',
  INFO_RESENDER: 'INFO_RESENDER',
  WRONG_FILE: 'WRONG_FILE',
};
